# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 258862f65395be68ae9f032da2c36f3e583e968eb13ced5dbe4388a477cdb26bacee7db8a354fcbbba301465a4fb051820baf962fc8232acf693d64472f47fd2

test:
  secret_key_base: 434b4205f5af3d18019269e1854614bdbc0bc3860e7add442b8d98e34ea02a22b6f36b6eda98b62493acf016fc6750410e6118299d5afcc010d60ce495cfba7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
